### ISSUE TITLE
the backend service cannot start

### ISSUE THREAD

**Issue by scottwansz** [CFETeam/weapp-demo-album#6]
root@10.154.252.34:/data/release/weapp-demo-album-master/server
# node app.js
/data/release/weapp-demo-album-master/server/middlewares/route_dispatcher.js:18
    let routePath;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/release/weapp-demo-album-master/server/app.js:28:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by scottwansz** [comment]
when I update the node to v6.6 and run again, get error as below:

root@10.154.252.34:/data/release/weapp-demo-album-master/server
# node -v
v6.6.0

root@10.154.252.34:/data/release/weapp-demo-album-master/server
# node app.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'cos-nodejs-sdk-v5/sdk/config'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/release/weapp-demo-album-master/server/services/cos/index.js:2:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by scottwansz** [comment]
did not find  'cos-nodejs-sdk-v5/sdk/config'
--------------------------------------------
root@10.154.252.34:/data/release/weapp-demo-album-master/server
# ll node_modules/cos-nodejs-sdk-v5/sdk/
total 120K
drwxr-xr-x 2 root 4.0K Jul 25 15:07 .
drwxr-xr-x 6 root 4.0K Jul 25 15:07 ..
-rw-r--r-- 1 root  23K Jun 17 13:59 advance.js
-rw-r--r-- 1 root  70K Jun 24 23:26 base.js
-rw-r--r-- 1 root  418 May 31 22:16 cos.js
-rw-r--r-- 1 root 6.8K Jun 17 13:59 util.js

**Comment by scottwansz** [comment]
the server can started after the modification
----------------------------------------------

root@10.154.252.34:/data/release/weapp-demo-album-master/server
# cat services/cos/index.js
const COS = require('cos-nodejs-sdk-v5')
//const _cosConfig = require('cos-nodejs-sdk-v5/sdk/config')
const config = require('../../config')

/**
 * init COS config
 * see: https://github.com/tencentyun/cos-nodejs-sdk-v5/blob/master/sdk/config.js#L24
 */
//_cosConfig.setAppInfo(config.cosAppId, config.cosSecretId, config.cosSecretKey);

var cos = new COS({
    AppId: config.cosAppId,
    SecretId: config.cosSecretId,
    SecretKey: config.cosSecretKey,
});

module.exports = cos
